# -*- coding: utf-8 -*-
"""Hackathon Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15qWbKsusOUM1ovBq7h-dgVgNkAg1NR3d
"""

import csv

def update_is_hcp(test_file, train_file):
    updated_data = []
    with open(test_file, 'r', encoding='latin-1') as test, open(train_file, 'r', encoding='latin-1') as train:
        test_reader = csv.DictReader(test)
        train_reader = csv.DictReader(train)

        train_data = {row['ID']: '1' for row in train_reader}

        for row in test_reader:
            id_value = row['ID']
            updated_data.append({'ID': id_value, 'IS_HCP': train_data.get(id_value, '1')})

    return updated_data

# Update IS_HCP values in Doceree-HCP_Train.csv based on IDs from Doceree-HCP_Test.csv
updated_data = update_is_hcp('Doceree-HCP_Test.csv', 'Doceree-HCP_Train.csv')

# Write the updated data to output.csv
with open('output.csv', 'w', newline='', encoding='latin-1') as file:
    fieldnames = ['ID', 'IS_HCP']
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(updated_data)

print("CSV file 'output.csv' has been created with updated ID and IS_HCP values.")